{
  "openapi": "3.0.0",
  "info": {
    "title": "Blogs API",
    "description": "An API designed to manage users and their posts in a database using an ORM",
    "contact": {
      "email": "samueldev8@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/",
      "description": "Test API"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "summary": "User Login",
        "description": "Logs user into system",
        "tags": ["Login"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "examples": {
                "login": {
                  "value": {
                    "email": "test@email.com",
                    "password": "test123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Logged",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Token"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "missing-fields": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "Some required fields are missing"
                    }
                  },
                  "user-does-not-exist": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "Invalid fields"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/user": {
      "get": {
        "summary": "Find all users",
        "description": "Return all users registered",
        "tags": ["User"],
        "security": [{ "TokenAuth": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  }
                },
                "example": [
                  {
                  "id": 1,
                  "displayName": "Lewis Hamilton",
                  "email": "lewishamilton@gmail.com",
                  "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                  },
                  {
                    "id": 2,
                    "displayName": "Michael Schumacher",
                    "email": "MichaelSchumacher@gmail.com",
                    "image": "https://sportbuzz.uol.com.br/media/_versions/gettyimages-52491565_widelg.jpg"
                  } 
                ]
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      },
      "post": {
        "summary": "Add a new user",
        "description": "Create a user and return a token",
        "tags": ["User"],
        "requestBody": {
          "$ref": "#/components/requestBodies/User"
        },
        "responses": {
          "201": {
            "description": "User registered",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Token"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "invalid-display-name": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "\"displayName\" length must be at least 8 characters long"
                    }
                  },
                  "invalid-email": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "\"email\" must be a valid email"
                    }
                  },
                  "invalid-password": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "\"password\" length must be at least 6 characters long"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "409": {
            "description": "User already registered",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 409,
                  "error": "Conflict",
                  "message": "User already registered"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/user/{id}": {
      "get": {
        "summary": "Find user by ID",
        "description": "Find user by ID",
        "tags": ["User"],
        "security": [{ "TokenAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "User by ID",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": 1,
                  "displayName": "Lewis Hamilton",
                  "email": "lewishamilton@gmail.com",
                  "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                }
              }
            }
          },
          "404": {
            "description":"User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "User does not exist"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/user/me": {
      "delete": {
        "summary": "Delete user",
        "tags": ["User"],
        "security": [{ "TokenAuth": [] }],
        "responses": {
          "204": {
            "description": "User deleted"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/categories": {
      "get": {
        "summary": "Find all categories",
        "description": "Return all categories registered",
        "tags": ["Categories"],
        "security": [{ "TokenAuth": [] }],
        "responses": {
          "204": {
            "description": "User deleted",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Categories"
                },
                "example": [
                  {
                    "id": 1,
                    "name": "Inovação"
                  },
                  {
                      "id": 2,
                      "name": "Escola"
                  }
                ]
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      },
      "post": {
        "summary": "Add a new category",
        "description": "Create a category",
        "tags": ["Categories"],
        "security": [{ "TokenAuth": [] }],
        "requestBody": {
          "$ref":"#/components/requestBodies/Category"
        },
        "responses": {
          "201": {
            "description": "Category created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Category"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "\"name\" is required"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/post": {
      "get": {
        "summary": "Find all posts",
        "description": "Return all posts registered",
        "tags": ["Post"],
        "security": [{ "TokenAuth": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "$ref": "#/components/schemas/Post",
                    "properties": {
                      "user": {
                        "$ref": "#/components/schemas/User"
                      },
                      "categories": {
                        "$ref": "#/components/schemas/Categories"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "id": 1,
                    "title": "Post do Ano",
                    "content": "Melhor post do ano",
                    "userId": 1,
                    "published": "2011-08-01T19:58:00.000Z",
                    "updated": "2011-08-01T19:58:51.000Z",
                    "user": {
                      "id": 1,
                      "displayName": "Lewis Hamilton",
                      "email": "lewishamilton@gmail.com",
                      "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                    },
                    "categories": [
                      {
                        "id": 1,
                        "name": "Inovação"
                      }
                    ]
                  }
                ]
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      },
      "post": {
        "summary": "Add a new post",
        "description": "Create a post",
        "tags": ["Post"],
        "security": [{ "TokenAuth": [] }],
        "requestBody": {
          "$ref":"#/components/requestBodies/Post"
        },
        "responses": {
          "201": {
            "description": "Post created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Post"
                },
                "example": {
                  "id": 3,
                  "title": "Latest updates, August 1st",
                  "content": "The whole text for the blog post goes here in this key",
                  "userId": 1,
                  "updated": "2022-05-18T18:00:01.196Z",
                  "published": "2022-05-18T18:00:01.196Z"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ApiResponse"
                },
                "examples": {
                  "blank-fields":{
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "Some required fields are missing"
                    }
                  },
                  "category-not-found":{
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "\"categoryIds\" not found"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/post/{id}": {
      "get": {
        "summary": "Find post by ID",
        "description": "Find post by ID",
        "tags": ["Post"],
        "security": [{ "TokenAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Post by ID",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Post",
                  "properties": {
                    "user": {
                      "$ref": "#/components/schemas/User"
                    },
                    "categories": {
                      "$ref": "#/components/schemas/Categories"
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "title": "Post do Ano",
                  "content": "Melhor post do ano",
                  "userId": 1,
                  "published": "2011-08-01T19:58:00.000Z",
                  "updated": "2011-08-01T19:58:51.000Z",
                  "user": {
                    "id": 1,
                    "displayName": "Lewis Hamilton",
                    "email": "lewishamilton@gmail.com",
                    "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                  },
                  "categories": [
                    {
                      "id": 1,
                      "name": "Inovação"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "404": {
            "description":"Post not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "Post does not exist"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      },
      "delete": {
        "summary": "Delete post",
        "tags": ["Post"],
        "security": [{ "TokenAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Post by ID",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Post deleted"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "404": {
            "description":"Post not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "Post does not exist"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      },
      "put": {
        "summary": "Update post",
        "tags": ["Post"],
        "security": [{ "TokenAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Post by ID",
            "required": true
          }
        ],
        "requestBody": {
          "$ref":"#/components/requestBodies/PostUpdate"
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Post",
                  "properties": {
                    "user": {
                      "$ref": "#/components/schemas/User"
                    },
                    "categories": {
                      "$ref": "#/components/schemas/Categories"
                    }
                  }
                },
                "example": {
                  "id": 3,
                  "title": "Latest updates, August 1st",
                  "content": "The whole text for the blog post goes here in this key",
                  "userId": 1,
                  "published": "2022-05-18T18:00:01.000Z",
                  "updated": "2022-05-18T18:07:32.000Z",
                  "user": {
                    "id": 1,
                    "displayName": "Lewis Hamilton",
                    "email": "lewishamilton@gmail.com",
                    "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                  },
                  "categories": [
                    {
                      "id": 1,
                      "name": "Inovação"
                    },
                    {
                      "id": 2,
                      "name": "Escola"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/ApiResponse"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "Some required fields are missing"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/post/search": {
      "get": {
        "summary": "Find posts by terms",
        "tags": ["Post"],
        "security": [{ "TokenAuth": [] }],
        "parameters": [
          {
            "allowEmptyValue": true,
            "name": "q",
            "in": "query",
            "description": "Terms about post content or title to search"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Post",
                  "properties": {
                    "user": {
                      "$ref": "#/components/schemas/User"
                    },
                    "categories": {
                      "$ref": "#/components/schemas/Categories"
                    }
                  }
                },
                "examples": {
                  "found-by-title-or-content": {
                    "value": [
                      {
                        "id": 2,
                        "title": "Vamos que vamos",
                        "content": "Foguete não tem ré",
                        "userId": 1,
                        "published": "2011-08-01T19:58:00.000Z",
                        "updated": "2011-08-01T19:58:51.000Z",
                        "user": {
                          "id": 1,
                          "displayName": "Lewis Hamilton",
                          "email": "lewishamilton@gmail.com",
                          "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                        },
                        "categories": [
                          {
                            "id": 2,
                            "name": "Escola"
                          }
                        ]
                      }
                  ]
                  },
                  "blank-term-search": {
                    "value": [
                      {
                        "id": 1,
                        "title": "Post do Ano",
                        "content": "Melhor post do ano",
                        "userId": 1,
                        "published": "2011-08-01T19:58:00.000Z",
                        "updated": "2011-08-01T19:58:51.000Z",
                        "user": {
                          "id": 1,
                          "displayName": "Lewis Hamilton",
                          "email": "lewishamilton@gmail.com",
                          "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                        },
                        "categories": [
                          {
                            "id": 1,
                            "name": "Inovação"
                          }
                        ]
                      },
                      {
                        "id": 2,
                        "title": "Vamos que vamos",
                        "content": "Foguete não tem ré",
                        "userId": 1,
                        "published": "2011-08-01T19:58:00.000Z",
                        "updated": "2011-08-01T19:58:51.000Z",
                        "user": {
                          "id": 1,
                          "displayName": "Lewis Hamilton",
                          "email": "lewishamilton@gmail.com",
                          "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                        },
                        "categories": [
                          {
                            "id": 2,
                            "name": "Escola"
                          }
                        ]
                      }
                    ]
                  },
                  "not-found": {
                    "value": []
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiResponse": {
        "type": "object",
        "properties": {
          "statusCode": {
            "type": "number"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "Categories": {
        "type": "array",
        "items": {
          "$ref":"#/components/schemas/Category"
        }
      },
      "Login": {
        "type": "object",
        "required": [
          "email",
          "password"
        ],
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Post": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "title": {
            "type": "string"
          },
          "content": {
            "type": "string"
          },
          "userId": {
            "type": "number"
          },
          "published": {
            "type": "string"
          },
          "updated": {
            "type": "string"
          }
        }
      },
      "PostBody": {
        "type": "object",
        "required": [
          "title",
          "content",
          "categoryIds"
        ],
        "properties": {
          "title": {
            "type": "string"
          },
          "content": {
            "type": "string"
          },
          "categoryIds": {
            "type": "array",
            "items": {
              "type": "number"
            }
          }
        }
      },
      "PostUpdateBody": {
        "type": "object",
        "required": [
          "title",
          "content"
        ],
        "properties": {
          "title": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        }
      },
      "Token": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "displayName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "image": {
            "type": "string"
          }
        }
      },
      "UserBody": {
        "type": "object",
        "required": [
          "displayName",
          "email",
          "password"
        ],
        "properties": {
          "displayName": {
            "type": "string",
            "minLength": 8
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string",
            "minLength": 6
          },
          "image": {
            "type": "string"
          }
        }
      }
    },
    "responses": {
      "GenericError": {
        "description": "Server Error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/ApiResponse"
            },
            "example": {
              "statusCode": 500,
              "error": "Internal Server Error",
              "message": "Unexpected error"
            }
          }
        }
      },
      "Unauthorized": {
        "description":"Missing token",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Error"
            },
            "example": {
              "statusCode": 401,
              "error": "Unauthorized",
              "message": "Token not found"
            }
          }
        }
      }
    },
    "requestBodies": {
      "Category": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": ["name"],
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            },
            "example": {
              "name": "Python"
            }
          }
        }
      },
      "Post": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PostBody"
            },
            "example": {
              "title": "Latest updates, August 1st",
              "content": "The whole text for the blog post goes here in this key",
              "categoryIds": [1, 2]
            }
          }
        }
      },
      "PostUpdate": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PostUpdateBody"
            },
            "example": {
              "title": "Latest updates, August 1st",
              "content": "The whole text for the blog post goes here in this key"
            }
          }
        }
      },
      "User": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/UserBody"
            },
            "example": {
              "displayName": "Brett Wiltshire",
              "email": "brett@email.com",
              "password": "123456",
              "image": "http://4.bp.blogspot.com/_YA50adQ-7vQ/S1gfR_6ufpI/AAAAAAAAAAk/1ErJGgRWZDg/S45/brett.png"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "TokenAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization"
      }
    }
  }
}