{
  "openapi": "3.0.0",
  "info": {
    "title": "Blogs API",
    "description": "Blogs API is a simplify system to manage users and posts from a blog.",
    "contact": {
      "email": "samueldev8@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/",
      "description": "Test API"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "summary": "User Login",
        "description": "Logs user into system",
        "tags": ["Login"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "examples": {
                "login": {
                  "value": {
                    "email": "test@email.com",
                    "password": "test123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Logged",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Token"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "missing-fields": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "Some required fields are missing"
                    }
                  },
                  "user-does-not-exist": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "Invalid fields"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/user": {
      "get": {
        "summary": "Find all users",
        "description": "Return all users registered",
        "tags": ["Users"],
        "security": [{ "TokenAuth": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Users"
                },
                "example": [
                  {
                  "id": 1,
                  "displayName": "Lewis Hamilton",
                  "email": "lewishamilton@gmail.com",
                  "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                  },
                  {
                    "id": 2,
                    "displayName": "Michael Schumacher",
                    "email": "MichaelSchumacher@gmail.com",
                    "image": "https://sportbuzz.uol.com.br/media/_versions/gettyimages-52491565_widelg.jpg"
                  } 
                ]
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      },
      "post": {
        "summary": "Add a new user",
        "description": "Create a user and return a token",
        "tags": ["Users"],
        "requestBody": {
          "$ref": "#/components/requestBodies/User"
        },
        "responses": {
          "201": {
            "description": "User registered",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Token"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "invalid-display-name": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "\"displayName\" length must be at least 8 characters long"
                    }
                  },
                  "invalid-email": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "\"email\" must be a valid email"
                    }
                  },
                  "invalid-password": {
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "\"password\" length must be at least 6 characters long"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "409": {
            "description": "User already registered",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 409,
                  "error": "Conflict",
                  "message": "User already registered"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/user/{id}": {
      "get": {
        "summary": "Find user by ID",
        "description": "Find user by ID",
        "tags": ["Users"],
        "security": [{ "TokenAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "User by ID",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": 1,
                  "displayName": "Lewis Hamilton",
                  "email": "lewishamilton@gmail.com",
                  "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg"
                }
              }
            }
          },
          "404": {
            "description":"User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "User does not exist"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/user/me": {
      "delete": {
        "summary": "Delete user",
        "tags": ["Users"],
        "security": [{ "TokenAuth": [] }],
        "responses": {
          "204": {
            "description": "User deleted"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    },
    "/categories": {
      "get": {
        "summary": "Find all categories",
        "description": "Return all categories registered",
        "tags": ["Categories"],
        "security": [{ "TokenAuth": [] }],
        "responses": {
          "204": {
            "description": "User deleted",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Categories"
                },
                "example": [
                  {
                    "id": 1,
                    "name": "Inovação"
                  },
                  {
                      "id": 2,
                      "name": "Escola"
                  }
                ]
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      },
      "post": {
        "summary": "Add a new category",
        "description": "Create a user and return a token",
        "tags": ["Categories"],
        "security": [{ "TokenAuth": [] }],
        "requestBody": {
          "$ref":"#/components/requestBodies/Category"
        },
        "responses": {
          "201": {
            "description": "Category created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Category"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "\"name\" is required"
                }
              }
            }
          },
          "default": {
            "$ref": "#/components/responses/GenericError"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "displayName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "image": {
            "type": "string"
          }
        }
      },
      "UserSignUp": {
        "type": "object",
        "properties": {
          "displayName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "image": {
            "type": "string"
          }
        }
      },
      "Users":{
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/User"
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "Categories": {
        "type": "array",
        "items": {
          "$ref":"#/components/schemas/Category"
        }
      },
      "Post": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "content": {
            "type": "string"
          },
          "categoryIds": {
            "type": "array",
            "items": {
              "type": "number"
            }
          }
        }
      },
      "Token": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string"
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "statusCode": {
            "type": "number"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      }
    },
    "responses": {
      "Unauthorized": {
        "description":"Missing token",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Error"
            },
            "example": {
              "statusCode": 401,
              "error": "Unauthorized",
              "message": "Token not found"
            }
          }
        }
      },
      "GenericError": {
        "description": "Server Error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Error"
            },
            "example": {
              "statusCode": 500,
              "error": "Internal Server Error",
              "message": "Unexpected error"
            }
          }
        }
      }
    },
    "requestBodies": {
      "User": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/UserSignUp"
            },
            "example": {
              "displayName": "Brett Wiltshire",
              "email": "brett@email.com",
              "password": "123456",
              "image": "http://4.bp.blogspot.com/_YA50adQ-7vQ/S1gfR_6ufpI/AAAAAAAAAAk/1ErJGgRWZDg/S45/brett.png"
            }
          }
        }
      },
      "Category": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                }
              }
            },
            "example": {
              "name": "Python"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "TokenAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization"
      }
    }
  }
}